
export default{
    REST_COUNTRY: process.env.REACT_APP_REST_COUNTRY,
    CALENDAR_URL: process.env.REACT_APP_CALENDAR_URL,
    CALENDAR_API_KEY: process.env.REACT_APP_CALENDAR_API_KEY,
    YOUTUBE_URL: process.env.REACT_APP_YOUTUBE_URL,
    YOUTUBE_API: process.env.YOUTUBE_API
    
}